services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - app-network
    volumes:
      - /usr/bin/dine-dash/.env:/app/frontend/.env

networks:
  app-network:
    driver: bridge